[package]
name = "ideabase"
version = "1.0.0"
edition = "2024"
description = "BaaS powered by AI, 兼具安全与性能的国产Firebase！"
authors = [
    "ReliefZk <reliefzk@gmail.com>",
]
keywords = ["baas", "ai-baas", "firebase", "supabase"]

[dependencies]
# 日志相关
log = { version = "0.4" }
tklog = { version = "0.2" }

# 异步和并发
tokio = { version = "1", features = ["full"] }

# Web框架
http = { version = "0.2" }
actix-web = { version = "4" }
actix-cors = { version = "0.7" }

# 数据库
sqlx = { version = "0.8", features = ["mysql", "chrono", "rust_decimal"] }

# 序列化/反序列化
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1" }

# 配置和工具
figment = { version = "0.10", features = ["yaml"] }
chrono = { version = "0.4", features = ["serde"] }
regex = { version = "1" }

# ID生成和哈希
uuid7 = { version = "1.1" }
rustflake = { version = "0.1.1" }

# 安全相关
base64 = { version = "0.22" }
jsonwebtoken = { version = "9" }
argon2 = { version = "0.5", default-features = false, features = ["std", "alloc", "password-hash", "rand"] }


# 工具和辅助库
fnv = { version = "1.0" }
lazy_static = { version = "1" }
once_cell = { version = "1.21" }

